-- Cobertura Lopesul extraída da página pública de áreas atendidas do SSW.
insert into public.cobertura_cidades (transportadora_id, uf, cidade)
values
  ('lopesul', 'BA', 'Barreiras'),
  ('lopesul', 'BA', 'Feira De Santana'),
  ('lopesul', 'BA', 'Luis Eduardo Magalhaes'),
  ('lopesul', 'BA', 'Salvador'),
  ('lopesul', 'BA', 'Santa Maria Da Vitoria'),
  ('lopesul', 'BA', 'Vitoria Da Conquista'),
  ('lopesul', 'GO', 'Abadia De Goias'),
  ('lopesul', 'GO', 'Abadiania'),
  ('lopesul', 'GO', 'Acreuna'),
  ('lopesul', 'GO', 'Adelandia'),
  ('lopesul', 'GO', 'Agua Fria De Goias'),
  ('lopesul', 'GO', 'Agua Limpa'),
  ('lopesul', 'GO', 'Aguas Lindas De Goias'),
  ('lopesul', 'GO', 'Alexania'),
  ('lopesul', 'GO', 'Aloandia'),
  ('lopesul', 'GO', 'Alto Horizonte'),
  ('lopesul', 'GO', 'Alto Paraiso De Goias'),
  ('lopesul', 'GO', 'Alvorada Do Norte'),
  ('lopesul', 'GO', 'Amaralina'),
  ('lopesul', 'GO', 'Americano Do Brasil'),
  ('lopesul', 'GO', 'Amorinopolis'),
  ('lopesul', 'GO', 'Anapolis'),
  ('lopesul', 'GO', 'Anhanguera'),
  ('lopesul', 'GO', 'Anicuns'),
  ('lopesul', 'GO', 'Aparecida De Goiania'),
  ('lopesul', 'GO', 'Aparecida De Goias'),
  ('lopesul', 'GO', 'Aparecida Do Rio Doce'),
  ('lopesul', 'GO', 'Apore'),
  ('lopesul', 'GO', 'Aracu'),
  ('lopesul', 'GO', 'Aragarcas'),
  ('lopesul', 'GO', 'Aragoiania'),
  ('lopesul', 'GO', 'Araguapaz'),
  ('lopesul', 'GO', 'Arenopolis'),
  ('lopesul', 'GO', 'Aruana'),
  ('lopesul', 'GO', 'Aurilandia'),
  ('lopesul', 'GO', 'Avelinopolis'),
  ('lopesul', 'GO', 'Baliza'),
  ('lopesul', 'GO', 'Barro Alto'),
  ('lopesul', 'GO', 'Bela Vista De Goias'),
  ('lopesul', 'GO', 'Bom Jardim De Goias'),
  ('lopesul', 'GO', 'Bom Jesus'),
  ('lopesul', 'GO', 'Bonfinopolis'),
  ('lopesul', 'GO', 'Bonopolis'),
  ('lopesul', 'GO', 'Brazabrantes'),
  ('lopesul', 'GO', 'Britania'),
  ('lopesul', 'GO', 'Buriti Alegre'),
  ('lopesul', 'GO', 'Buriti De Goias'),
  ('lopesul', 'GO', 'Buritinopolis'),
  ('lopesul', 'GO', 'Cabeceiras'),
  ('lopesul', 'GO', 'Cachoeira Alta'),
  ('lopesul', 'GO', 'Cachoeira De Goias'),
  ('lopesul', 'GO', 'Cachoeira Dourada'),
  ('lopesul', 'GO', 'Cacu'),
  ('lopesul', 'GO', 'Caiaponia'),
  ('lopesul', 'GO', 'Calcilandia'),
  ('lopesul', 'GO', 'Caldas Novas'),
  ('lopesul', 'GO', 'Caldazinha'),
  ('lopesul', 'GO', 'Campestre De Goias'),
  ('lopesul', 'GO', 'Campinacu'),
  ('lopesul', 'GO', 'Campinorte'),
  ('lopesul', 'GO', 'Campo Alegre De Goias'),
  ('lopesul', 'GO', 'Campo Limpo De Goias'),
  ('lopesul', 'GO', 'Campos Belos'),
  ('lopesul', 'GO', 'Campos Verdes'),
  ('lopesul', 'GO', 'Carmo Do Rio Verde'),
  ('lopesul', 'GO', 'Castelandia'),
  ('lopesul', 'GO', 'Catalao'),
  ('lopesul', 'GO', 'Caturai'),
  ('lopesul', 'GO', 'Cavalcante'),
  ('lopesul', 'GO', 'Ceres'),
  ('lopesul', 'GO', 'Cezarina'),
  ('lopesul', 'GO', 'Chapadao Do Ceu'),
  ('lopesul', 'GO', 'Cidade Ocidental'),
  ('lopesul', 'GO', 'Cocalzinho De Goias'),
  ('lopesul', 'GO', 'Colinas Do Sul'),
  ('lopesul', 'GO', 'Corrego Do Ouro'),
  ('lopesul', 'GO', 'Corumba De Goias'),
  ('lopesul', 'GO', 'Corumbaiba'),
  ('lopesul', 'GO', 'Cristalina'),
  ('lopesul', 'GO', 'Cristianopolis'),
  ('lopesul', 'GO', 'Crixas'),
  ('lopesul', 'GO', 'Crominia'),
  ('lopesul', 'GO', 'Cumari'),
  ('lopesul', 'GO', 'Damianopolis'),
  ('lopesul', 'GO', 'Damolandia'),
  ('lopesul', 'GO', 'Davinopolis'),
  ('lopesul', 'GO', 'Diorama'),
  ('lopesul', 'GO', 'Divinopolis De Goias'),
  ('lopesul', 'GO', 'Doverlandia'),
  ('lopesul', 'GO', 'Edealina'),
  ('lopesul', 'GO', 'Edeia'),
  ('lopesul', 'GO', 'Estrela Do Norte'),
  ('lopesul', 'GO', 'Faina'),
  ('lopesul', 'GO', 'Fazenda Nova'),
  ('lopesul', 'GO', 'Firminopolis'),
  ('lopesul', 'GO', 'Flores De Goias'),
  ('lopesul', 'GO', 'Formosa'),
  ('lopesul', 'GO', 'Formoso'),
  ('lopesul', 'GO', 'Gameleira De Goias'),
  ('lopesul', 'GO', 'Goianapolis'),
  ('lopesul', 'GO', 'Goiandira'),
  ('lopesul', 'GO', 'Goianesia'),
  ('lopesul', 'GO', 'Goiania'),
  ('lopesul', 'GO', 'Goianira'),
  ('lopesul', 'GO', 'Goias'),
  ('lopesul', 'GO', 'Goiatuba'),
  ('lopesul', 'GO', 'Gouvelandia'),
  ('lopesul', 'GO', 'Guapo'),
  ('lopesul', 'GO', 'Guaraita'),
  ('lopesul', 'GO', 'Guarani De Goias'),
  ('lopesul', 'GO', 'Guarinos'),
  ('lopesul', 'GO', 'Heitorai'),
  ('lopesul', 'GO', 'Hidrolandia'),
  ('lopesul', 'GO', 'Hidrolina'),
  ('lopesul', 'GO', 'Iaciara'),
  ('lopesul', 'GO', 'Inaciolandia'),
  ('lopesul', 'GO', 'Indiara'),
  ('lopesul', 'GO', 'Inhumas'),
  ('lopesul', 'GO', 'Ipameri'),
  ('lopesul', 'GO', 'Ipiranga De Goias'),
  ('lopesul', 'GO', 'Ipora'),
  ('lopesul', 'GO', 'Israelandia'),
  ('lopesul', 'GO', 'Itaberai'),
  ('lopesul', 'GO', 'Itaguari'),
  ('lopesul', 'GO', 'Itaguaru'),
  ('lopesul', 'GO', 'Itaja'),
  ('lopesul', 'GO', 'Itapaci'),
  ('lopesul', 'GO', 'Itapirapua'),
  ('lopesul', 'GO', 'Itapuranga'),
  ('lopesul', 'GO', 'Itaruma'),
  ('lopesul', 'GO', 'Itaucu'),
  ('lopesul', 'GO', 'Itumbiara'),
  ('lopesul', 'GO', 'Ivolandia'),
  ('lopesul', 'GO', 'Jandaia'),
  ('lopesul', 'GO', 'Jaragua'),
  ('lopesul', 'GO', 'Jatai'),
  ('lopesul', 'GO', 'Jaupaci'),
  ('lopesul', 'GO', 'Jesupolis'),
  ('lopesul', 'GO', 'Joviania'),
  ('lopesul', 'GO', 'Jussara'),
  ('lopesul', 'GO', 'Lagoa Santa'),
  ('lopesul', 'GO', 'Leopoldo De Bulhoes'),
  ('lopesul', 'GO', 'Luziania'),
  ('lopesul', 'GO', 'Mairipotaba'),
  ('lopesul', 'GO', 'Mambai'),
  ('lopesul', 'GO', 'Mara Rosa'),
  ('lopesul', 'GO', 'Marzagao'),
  ('lopesul', 'GO', 'Matrincha'),
  ('lopesul', 'GO', 'Maurilandia'),
  ('lopesul', 'GO', 'Mimoso De Goias'),
  ('lopesul', 'GO', 'Minacu'),
  ('lopesul', 'GO', 'Mineiros'),
  ('lopesul', 'GO', 'Moipora'),
  ('lopesul', 'GO', 'Monte Alegre De Goias'),
  ('lopesul', 'GO', 'Montes Claros De Goias'),
  ('lopesul', 'GO', 'Montividiu'),
  ('lopesul', 'GO', 'Montividiu Do Norte'),
  ('lopesul', 'GO', 'Morrinhos'),
  ('lopesul', 'GO', 'Morro Agudo De Goias'),
  ('lopesul', 'GO', 'Mossamedes'),
  ('lopesul', 'GO', 'Mozarlandia'),
  ('lopesul', 'GO', 'Mundo Novo'),
  ('lopesul', 'GO', 'Mutunopolis'),
  ('lopesul', 'GO', 'Nazario'),
  ('lopesul', 'GO', 'Neropolis'),
  ('lopesul', 'GO', 'Niquelandia'),
  ('lopesul', 'GO', 'Nova America'),
  ('lopesul', 'GO', 'Nova Aurora'),
  ('lopesul', 'GO', 'Nova Crixas'),
  ('lopesul', 'GO', 'Nova Gloria'),
  ('lopesul', 'GO', 'Nova Iguacu De Goias'),
  ('lopesul', 'GO', 'Nova Roma'),
  ('lopesul', 'GO', 'Nova Veneza'),
  ('lopesul', 'GO', 'Novo Brasil'),
  ('lopesul', 'GO', 'Novo Gama'),
  ('lopesul', 'GO', 'Novo Planalto'),
  ('lopesul', 'GO', 'Orizona'),
  ('lopesul', 'GO', 'Ouro Verde De Goias'),
  ('lopesul', 'GO', 'Ouvidor'),
  ('lopesul', 'GO', 'Padre Bernardo'),
  ('lopesul', 'GO', 'Palestina De Goias'),
  ('lopesul', 'GO', 'Palmeiras De Goias'),
  ('lopesul', 'GO', 'Palmelo'),
  ('lopesul', 'GO', 'Palminopolis'),
  ('lopesul', 'GO', 'Panama'),
  ('lopesul', 'GO', 'Paranaiguara'),
  ('lopesul', 'GO', 'Parauna'),
  ('lopesul', 'GO', 'Perolandia'),
  ('lopesul', 'GO', 'Petrolina De Goias'),
  ('lopesul', 'GO', 'Pilar De Goias'),
  ('lopesul', 'GO', 'Piracanjuba'),
  ('lopesul', 'GO', 'Piranhas'),
  ('lopesul', 'GO', 'Pirenopolis'),
  ('lopesul', 'GO', 'Pires Do Rio'),
  ('lopesul', 'GO', 'Planaltina'),
  ('lopesul', 'GO', 'Pontalina'),
  ('lopesul', 'GO', 'Porangatu'),
  ('lopesul', 'GO', 'Porteirao'),
  ('lopesul', 'GO', 'Portelandia'),
  ('lopesul', 'GO', 'Posse'),
  ('lopesul', 'GO', 'Professor Jamil'),
  ('lopesul', 'GO', 'Quirinopolis'),
  ('lopesul', 'GO', 'Rialma'),
  ('lopesul', 'GO', 'Rianapolis'),
  ('lopesul', 'GO', 'Rio Quente'),
  ('lopesul', 'GO', 'Rio Verde'),
  ('lopesul', 'GO', 'Rosalandia'),
  ('lopesul', 'GO', 'Rubiataba'),
  ('lopesul', 'GO', 'Sanclerlandia'),
  ('lopesul', 'GO', 'Santa Barbara De Goias'),
  ('lopesul', 'GO', 'Santa Cruz De Goias'),
  ('lopesul', 'GO', 'Santa Fe De Goias'),
  ('lopesul', 'GO', 'Santa Helena De Goias'),
  ('lopesul', 'GO', 'Santa Isabel'),
  ('lopesul', 'GO', 'Santa Rita Do Araguaia'),
  ('lopesul', 'GO', 'Santa Rita Do Novo Destino'),
  ('lopesul', 'GO', 'Santa Rosa'),
  ('lopesul', 'GO', 'Santa Rosa De Goias'),
  ('lopesul', 'GO', 'Santa Tereza De Goias'),
  ('lopesul', 'GO', 'Santa Terezinha De Goias'),
  ('lopesul', 'GO', 'Santo Antonio Da Barra'),
  ('lopesul', 'GO', 'Santo Antonio De Goias'),
  ('lopesul', 'GO', 'Santo Antonio Do Descoberto'),
  ('lopesul', 'GO', 'Sao Domingos'),
  ('lopesul', 'GO', 'Sao Francisco De Goias'),
  ('lopesul', 'GO', 'Sao Gabriel De Goias'),
  ('lopesul', 'GO', 'Sao Joao D Alianca'),
  ('lopesul', 'GO', 'Sao Joao Da Parauna'),
  ('lopesul', 'GO', 'Sao Luis De Montes Belos'),
  ('lopesul', 'GO', 'Sao Luiz Do Norte'),
  ('lopesul', 'GO', 'Sao Miguel Do Araguaia'),
  ('lopesul', 'GO', 'Sao Miguel Do Passa Quatro'),
  ('lopesul', 'GO', 'Sao Patricio'),
  ('lopesul', 'GO', 'Sao Simao'),
  ('lopesul', 'GO', 'Senador Canedo'),
  ('lopesul', 'GO', 'Serranopolis'),
  ('lopesul', 'GO', 'Silvania'),
  ('lopesul', 'GO', 'Simolandia'),
  ('lopesul', 'GO', 'Sitio D Abadia'),
  ('lopesul', 'GO', 'Souzalandia'),
  ('lopesul', 'GO', 'Taquaral De Goias'),
  ('lopesul', 'GO', 'Teresina De Goias'),
  ('lopesul', 'GO', 'Terezopolis De Goias'),
  ('lopesul', 'GO', 'Tres Ranchos'),
  ('lopesul', 'GO', 'Trindade'),
  ('lopesul', 'GO', 'Trombas'),
  ('lopesul', 'GO', 'Turvania'),
  ('lopesul', 'GO', 'Turvelandia'),
  ('lopesul', 'GO', 'Uirapuru'),
  ('lopesul', 'GO', 'Uruacu'),
  ('lopesul', 'GO', 'Uruana'),
  ('lopesul', 'GO', 'Uruita'),
  ('lopesul', 'GO', 'Urutai'),
  ('lopesul', 'GO', 'Valparaiso De Goias'),
  ('lopesul', 'GO', 'Varjao'),
  ('lopesul', 'GO', 'Vianopolis'),
  ('lopesul', 'GO', 'Vicentinopolis'),
  ('lopesul', 'GO', 'Vila Boa'),
  ('lopesul', 'GO', 'Vila Propicio'),
  ('lopesul', 'MS', 'Aparecida Do Taboado'),
  ('lopesul', 'MS', 'Campo Grande'),
  ('lopesul', 'MS', 'Cassilandia'),
  ('lopesul', 'MS', 'Chapadao Do Sul'),
  ('lopesul', 'MS', 'Costa Rica'),
  ('lopesul', 'MS', 'Coxim'),
  ('lopesul', 'MS', 'Dourados'),
  ('lopesul', 'MS', 'Fatima Do Sul'),
  ('lopesul', 'MS', 'Itapora'),
  ('lopesul', 'MS', 'Juti'),
  ('lopesul', 'MS', 'Maracaju'),
  ('lopesul', 'MS', 'Navirai'),
  ('lopesul', 'MS', 'Panambi'),
  ('lopesul', 'MS', 'Paranaiba'),
  ('lopesul', 'MS', 'Pirapora'),
  ('lopesul', 'MS', 'Ponta Pora'),
  ('lopesul', 'MS', 'Rio Brilhante'),
  ('lopesul', 'MS', 'Rio Verde De Mato Grosso'),
  ('lopesul', 'MS', 'Sao Gabriel Do Oeste'),
  ('lopesul', 'MS', 'Sidrolandia'),
  ('lopesul', 'MS', 'Tres Lagoas'),
  ('lopesul', 'MT', 'Agua Boa'),
  ('lopesul', 'MT', 'Alta Floresta'),
  ('lopesul', 'MT', 'Alto Araguaia'),
  ('lopesul', 'MT', 'Alto Boa Vista'),
  ('lopesul', 'MT', 'Alto Taquari'),
  ('lopesul', 'MT', 'Aripuana'),
  ('lopesul', 'MT', 'Barra Do Garcas'),
  ('lopesul', 'MT', 'Bom Jesus Do Araguaia'),
  ('lopesul', 'MT', 'Brasnorte'),
  ('lopesul', 'MT', 'Caceres'),
  ('lopesul', 'MT', 'Campo Novo Do Parecis'),
  ('lopesul', 'MT', 'Campo Verde'),
  ('lopesul', 'MT', 'Canabrava Do Norte'),
  ('lopesul', 'MT', 'Canarana'),
  ('lopesul', 'MT', 'Carlinda'),
  ('lopesul', 'MT', 'Castanheira'),
  ('lopesul', 'MT', 'Colider'),
  ('lopesul', 'MT', 'Colniza'),
  ('lopesul', 'MT', 'Confresa'),
  ('lopesul', 'MT', 'Cotriguacu'),
  ('lopesul', 'MT', 'Cuiaba'),
  ('lopesul', 'MT', 'Guaranta Do Norte'),
  ('lopesul', 'MT', 'Itauba'),
  ('lopesul', 'MT', 'Juara'),
  ('lopesul', 'MT', 'Juina'),
  ('lopesul', 'MT', 'Juruena'),
  ('lopesul', 'MT', 'Lucas Do Rio Verde'),
  ('lopesul', 'MT', 'Luciara'),
  ('lopesul', 'MT', 'Matupa'),
  ('lopesul', 'MT', 'Nova Mutum'),
  ('lopesul', 'MT', 'Nova Santa Helena'),
  ('lopesul', 'MT', 'Nova Xavantina'),
  ('lopesul', 'MT', 'Novo Horizonte Do Norte'),
  ('lopesul', 'MT', 'Novo Santo Antonio'),
  ('lopesul', 'MT', 'Paranatinga'),
  ('lopesul', 'MT', 'Peixoto De Azevedo'),
  ('lopesul', 'MT', 'Pontes E Lacerda'),
  ('lopesul', 'MT', 'Porto Alegre Do Norte'),
  ('lopesul', 'MT', 'Porto Dos Gauchos'),
  ('lopesul', 'MT', 'Primavera Do Leste'),
  ('lopesul', 'MT', 'Querencia'),
  ('lopesul', 'MT', 'Ribeirao Cascalheira'),
  ('lopesul', 'MT', 'Rondonopolis'),
  ('lopesul', 'MT', 'Santa Cruz Do Xingu'),
  ('lopesul', 'MT', 'Santa Terezinha'),
  ('lopesul', 'MT', 'Sao Felix Do Araguaia'),
  ('lopesul', 'MT', 'Sapezal'),
  ('lopesul', 'MT', 'Serra Nova Dourada'),
  ('lopesul', 'MT', 'Sinop'),
  ('lopesul', 'MT', 'Sorriso'),
  ('lopesul', 'MT', 'Tabapora'),
  ('lopesul', 'MT', 'Tangara Da Serra'),
  ('lopesul', 'MT', 'Terra Nova Do Norte'),
  ('lopesul', 'MT', 'Varzea Grande'),
  ('lopesul', 'MT', 'Vila Rica'),
  ('lopesul', 'PA', 'Castelo Dos Sonhos'),
  ('lopesul', 'PA', 'Novo Progresso'),
  ('lopesul', 'PE', 'Vitoria De Santo Antao'),
  ('lopesul', 'PR', 'Agua Boa'),
  ('lopesul', 'PR', 'Apucarana'),
  ('lopesul', 'PR', 'Aquidaban'),
  ('lopesul', 'PR', 'Arapongas'),
  ('lopesul', 'PR', 'Araruna'),
  ('lopesul', 'PR', 'Areia Branca Dos Assis'),
  ('lopesul', 'PR', 'Assis Chateaubriand'),
  ('lopesul', 'PR', 'Barao De Lucena'),
  ('lopesul', 'PR', 'Barracao'),
  ('lopesul', 'PR', 'Boa Esperanca'),
  ('lopesul', 'PR', 'Bom Jesus Do Sul'),
  ('lopesul', 'PR', 'Cafelandia'),
  ('lopesul', 'PR', 'Cambe'),
  ('lopesul', 'PR', 'Cambira'),
  ('lopesul', 'PR', 'Campo Mourao'),
  ('lopesul', 'PR', 'Canzianopolis'),
  ('lopesul', 'PR', 'Cascavel'),
  ('lopesul', 'PR', 'Conciolandia'),
  ('lopesul', 'PR', 'Covo'),
  ('lopesul', 'PR', 'Dez De Maio'),
  ('lopesul', 'PR', 'Engenheiro Beltrao'),
  ('lopesul', 'PR', 'Entre Rios'),
  ('lopesul', 'PR', 'Farol'),
  ('lopesul', 'PR', 'Flor Da Serra Do Sul'),
  ('lopesul', 'PR', 'Floriano'),
  ('lopesul', 'PR', 'Foz Do Iguacu'),
  ('lopesul', 'PR', 'Francisco Beltrao'),
  ('lopesul', 'PR', 'Goioere'),
  ('lopesul', 'PR', 'Guaipora'),
  ('lopesul', 'PR', 'Iguatemi'),
  ('lopesul', 'PR', 'Irere'),
  ('lopesul', 'PR', 'Ivailandia'),
  ('lopesul', 'PR', 'Jandaia Do Sul'),
  ('lopesul', 'PR', 'Janiopolis'),
  ('lopesul', 'PR', 'Juranda'),
  ('lopesul', 'PR', 'Londrina'),
  ('lopesul', 'PR', 'Malu'),
  ('lopesul', 'PR', 'Mandaguacu'),
  ('lopesul', 'PR', 'Mandaguari'),
  ('lopesul', 'PR', 'Marcionopolis'),
  ('lopesul', 'PR', 'Marechal Candido Rondon'),
  ('lopesul', 'PR', 'Marialva'),
  ('lopesul', 'PR', 'Maringa'),
  ('lopesul', 'PR', 'Maripa'),
  ('lopesul', 'PR', 'Maristela'),
  ('lopesul', 'PR', 'Marmeleiro'),
  ('lopesul', 'PR', 'Medianeira'),
  ('lopesul', 'PR', 'Monjolinho'),
  ('lopesul', 'PR', 'Nova Santa Rosa'),
  ('lopesul', 'PR', 'Novo Sarandi'),
  ('lopesul', 'PR', 'Paicandu'),
  ('lopesul', 'PR', 'Palotina'),
  ('lopesul', 'PR', 'Pato Branco'),
  ('lopesul', 'PR', 'Peabiru'),
  ('lopesul', 'PR', 'Rancho Alegre'),
  ('lopesul', 'PR', 'Realeza'),
  ('lopesul', 'PR', 'Santo Antonio Do Sudoeste'),
  ('lopesul', 'PR', 'Sao Jose'),
  ('lopesul', 'PR', 'Sao Jose Do Ivai'),
  ('lopesul', 'PR', 'Sao Lourenco'),
  ('lopesul', 'PR', 'Sao Miguel Do Cambui'),
  ('lopesul', 'PR', 'Sao Silvestre'),
  ('lopesul', 'PR', 'Sarandi'),
  ('lopesul', 'PR', 'Toledo'),
  ('lopesul', 'PR', 'Warta'),
  ('lopesul', 'RS', 'Aguas Claras'),
  ('lopesul', 'RS', 'Ajuricaba'),
  ('lopesul', 'RS', 'Alegria'),
  ('lopesul', 'RS', 'Almirante Tamandare Do Sul'),
  ('lopesul', 'RS', 'Alto Alegre'),
  ('lopesul', 'RS', 'Ametista Do Sul'),
  ('lopesul', 'RS', 'Augusto Pestana'),
  ('lopesul', 'RS', 'Boa Vista Do Burica'),
  ('lopesul', 'RS', 'Bossoroca'),
  ('lopesul', 'RS', 'Bozano'),
  ('lopesul', 'RS', 'Camargo'),
  ('lopesul', 'RS', 'Campina Das Missoes'),
  ('lopesul', 'RS', 'Campos Borges'),
  ('lopesul', 'RS', 'Candido Godoi'),
  ('lopesul', 'RS', 'Carazinho'),
  ('lopesul', 'RS', 'Casca'),
  ('lopesul', 'RS', 'Catuipe'),
  ('lopesul', 'RS', 'Chapada'),
  ('lopesul', 'RS', 'Charrua'),
  ('lopesul', 'RS', 'Colorado'),
  ('lopesul', 'RS', 'Condor'),
  ('lopesul', 'RS', 'Coronel Barros'),
  ('lopesul', 'RS', 'Cruz Alta'),
  ('lopesul', 'RS', 'Doutor Mauricio Cardoso'),
  ('lopesul', 'RS', 'Erebango'),
  ('lopesul', 'RS', 'Erechim'),
  ('lopesul', 'RS', 'Ernestina'),
  ('lopesul', 'RS', 'Erval Seco'),
  ('lopesul', 'RS', 'Espumoso'),
  ('lopesul', 'RS', 'Estacao'),
  ('lopesul', 'RS', 'Estrela Velha'),
  ('lopesul', 'RS', 'Floriano Peixoto'),
  ('lopesul', 'RS', 'Fortaleza Dos Valos'),
  ('lopesul', 'RS', 'Frederico Westphalen'),
  ('lopesul', 'RS', 'Gentil'),
  ('lopesul', 'RS', 'Getulio Vargas'),
  ('lopesul', 'RS', 'Girua'),
  ('lopesul', 'RS', 'Horizontina'),
  ('lopesul', 'RS', 'Ibirapuita'),
  ('lopesul', 'RS', 'Ibiruba'),
  ('lopesul', 'RS', 'Ijui'),
  ('lopesul', 'RS', 'Independencia'),
  ('lopesul', 'RS', 'Ipiranga Do Sul'),
  ('lopesul', 'RS', 'Jacuizinho'),
  ('lopesul', 'RS', 'Joia'),
  ('lopesul', 'RS', 'Lagoa Dos Tres Cantos'),
  ('lopesul', 'RS', 'Marau'),
  ('lopesul', 'RS', 'Monte Alverne'),
  ('lopesul', 'RS', 'Mormaco'),
  ('lopesul', 'RS', 'Nao-me-toque'),
  ('lopesul', 'RS', 'Nicolau Vergueiro'),
  ('lopesul', 'RS', 'Nova Alvorada'),
  ('lopesul', 'RS', 'Nova Candelaria'),
  ('lopesul', 'RS', 'Novo Machado'),
  ('lopesul', 'RS', 'Palmeira Das Missoes'),
  ('lopesul', 'RS', 'Palmitinho'),
  ('lopesul', 'RS', 'Panambi'),
  ('lopesul', 'RS', 'Passo Fundo'),
  ('lopesul', 'RS', 'Pejucara'),
  ('lopesul', 'RS', 'Planalto'),
  ('lopesul', 'RS', 'Porto Lucena'),
  ('lopesul', 'RS', 'Porto Maua'),
  ('lopesul', 'RS', 'Porto Vera Cruz'),
  ('lopesul', 'RS', 'Porto Xavier'),
  ('lopesul', 'RS', 'Quinta'),
  ('lopesul', 'RS', 'Quinze De Novembro'),
  ('lopesul', 'RS', 'Rodeio Bonito'),
  ('lopesul', 'RS', 'Saldanha Marinho'),
  ('lopesul', 'RS', 'Salto Do Jacui'),
  ('lopesul', 'RS', 'Santa Barbara Do Sul'),
  ('lopesul', 'RS', 'Santa Rosa'),
  ('lopesul', 'RS', 'Santo Angelo'),
  ('lopesul', 'RS', 'Santo Antonio Do Planalto'),
  ('lopesul', 'RS', 'Santo Augusto'),
  ('lopesul', 'RS', 'Santo Cristo'),
  ('lopesul', 'RS', 'Sao Jose Do Inhacora'),
  ('lopesul', 'RS', 'Sao Martinho'),
  ('lopesul', 'RS', 'Sao Paulo Das Missoes'),
  ('lopesul', 'RS', 'Seberi'),
  ('lopesul', 'RS', 'Selbach'),
  ('lopesul', 'RS', 'Senador Salgado Filho'),
  ('lopesul', 'RS', 'Serafina Correa'),
  ('lopesul', 'RS', 'Sertao'),
  ('lopesul', 'RS', 'Soledade'),
  ('lopesul', 'RS', 'Tapera'),
  ('lopesul', 'RS', 'Taquarucu Do Sul'),
  ('lopesul', 'RS', 'Tio Hugo'),
  ('lopesul', 'RS', 'Tres De Maio'),
  ('lopesul', 'RS', 'Tucunduva'),
  ('lopesul', 'RS', 'Tuparendi'),
  ('lopesul', 'RS', 'Ubiretama'),
  ('lopesul', 'RS', 'Victor Graeff'),
  ('lopesul', 'RS', 'Vila Maria'),
  ('lopesul', 'RS', 'Vista Alegre'),
  ('lopesul', 'SC', 'Chapeco'),
  ('lopesul', 'SC', 'Concordia'),
  ('lopesul', 'SC', 'Cordilheira Alta'),
  ('lopesul', 'SC', 'Cunha Pora'),
  ('lopesul', 'SC', 'Dionisio Cerqueira'),
  ('lopesul', 'SC', 'Maravilha'),
  ('lopesul', 'SC', 'Sao Miguel Do Oeste'),
  ('lopesul', 'SC', 'Xanxere'),
  ('lopesul', 'SC', 'Xaxim'),
  ('lopesul', 'SP', 'Andradina'),
  ('lopesul', 'SP', 'Aruja'),
  ('lopesul', 'SP', 'Barueri'),
  ('lopesul', 'SP', 'Bonfim Paulista'),
  ('lopesul', 'SP', 'Cacapava'),
  ('lopesul', 'SP', 'Caieiras'),
  ('lopesul', 'SP', 'Cajamar'),
  ('lopesul', 'SP', 'Campo Limpo Paulista'),
  ('lopesul', 'SP', 'Cotia'),
  ('lopesul', 'SP', 'Cruz Das Posses'),
  ('lopesul', 'SP', 'Cubatao'),
  ('lopesul', 'SP', 'Diadema'),
  ('lopesul', 'SP', 'Embu Das Artes'),
  ('lopesul', 'SP', 'Ferraz De Vasconcelos'),
  ('lopesul', 'SP', 'Guararema'),
  ('lopesul', 'SP', 'Guaruja'),
  ('lopesul', 'SP', 'Guarulhos'),
  ('lopesul', 'SP', 'Hortolandia'),
  ('lopesul', 'SP', 'Ilha Solteira'),
  ('lopesul', 'SP', 'Itapecerica Da Serra'),
  ('lopesul', 'SP', 'Itaquaquecetuba'),
  ('lopesul', 'SP', 'Itupeva'),
  ('lopesul', 'SP', 'Jacare'),
  ('lopesul', 'SP', 'Jacarei'),
  ('lopesul', 'SP', 'Jordanesia'),
  ('lopesul', 'SP', 'Jundiai'),
  ('lopesul', 'SP', 'Lacio'),
  ('lopesul', 'SP', 'Louveira'),
  ('lopesul', 'SP', 'Maua'),
  ('lopesul', 'SP', 'Mogi Das Cruzes'),
  ('lopesul', 'SP', 'Osasco'),
  ('lopesul', 'SP', 'Pindamonhangaba'),
  ('lopesul', 'SP', 'Poa'),
  ('lopesul', 'SP', 'Polvilho'),
  ('lopesul', 'SP', 'Praia Grande'),
  ('lopesul', 'SP', 'Presidente Prudente'),
  ('lopesul', 'SP', 'Santa Isabel'),
  ('lopesul', 'SP', 'Santo Andre'),
  ('lopesul', 'SP', 'Santos'),
  ('lopesul', 'SP', 'Sao Bernardo Do Campo'),
  ('lopesul', 'SP', 'Sao Caetano Do Sul'),
  ('lopesul', 'SP', 'Sao Jose Dos Campos'),
  ('lopesul', 'SP', 'Sao Paulo'),
  ('lopesul', 'SP', 'Sao Vicente'),
  ('lopesul', 'SP', 'Suzano'),
  ('lopesul', 'SP', 'Taboao Da Serra'),
  ('lopesul', 'SP', 'Taubate'),
  ('lopesul', 'SP', 'Valinhos'),
  ('lopesul', 'SP', 'Varzea Paulista'),
  ('lopesul', 'SP', 'Vinhedo')
on conflict (transportadora_id, uf, cidade_norm) do update
set cidade = excluded.cidade, updated_at = now();
